# Generated by Django 3.2.9 on 2021-12-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211206_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='empname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_no',
            new_name='empno',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_salary',
            new_name='empsalary',
        ),
    ]
